[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font"

[window.padding]
x = 4
y = 4

[[keyboard.bindings]]
key = "NumpadEnter"
chars = "\r"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B[13;2u"

[[keyboard.bindings]]
key = "Return"
mods = "Control"
chars = "\u001B[13;5u"

